### ISSUE TITLE
[BUG] add margin to navigation links

### ISSUE THREAD

**Issue by RakeshSangem** [RakeshSangem/portfolio#1]
## Issue:

There is space between the NavBar links. So add margin to navigation links.

![add margin](https://user-images.githubusercontent.com/107752425/192083910-2bed21cc-fbe8-4bc1-a5a0-83b717903ca8.png)

**Comment by abitsalihu** [comment]
Hey @RakeshSangem, I would like to help with this issue. :)

**Comment by RakeshSangem** [comment]
> Hey @RakeshSangem, I would like to help with this issue. :)

Sure! I assigned to you:)
