### ISSUE TITLE
[FEATURE] add functionality to dark/light mode icon

### ISSUE THREAD

**Issue by RakeshSangem** [RakeshSangem/portfolio#10]
Add functionality to dark/light mode icon.
- create CSS root variables

### Note: please use prettier to format the cod before you create PR

reference image
![Screenshot 2022-09-30 235914](https://user-images.githubusercontent.com/107752425/193334409-05ef8d04-64cd-44a8-8821-cc78ca9229f8.png)

**Comment by salted0dreams** [comment]
Can u pls assign me this issue? And pls send an example of the dark page.

**Comment by IayushCoderJOD** [comment]
Assign this to me I'm quite good in theme changing thanks @RakeshSangem

**Comment by RakeshSangem** [comment]
This issue already resolved. Reference #11
