### ISSUE TITLE
Adding Animation

### ISSUE THREAD

**Issue by AliReza1083** [RakeshSangem/portfolio#12]
### Is your feature request related to a problem? Please describe.**
NO

### Describe the solution you'd like**
I want to add animation

**Comment by RakeshSangem** [comment]
Could you explore what kind of changes you want to make?

**Comment by AliReza1083** [comment]
Like I did in Sharkfolio.
When you refresh the page, the texts are appearing.

**Comment by RakeshSangem** [comment]
Awesome, assigned to you:)

**Comment by RakeshSangem** [comment]
Task finished
