### ISSUE TITLE
[DOCS] improve the documentation

### ISSUE THREAD

**Issue by RakeshSangem** [RakeshSangem/portfolio#16]
Improve the project's README.md

- add license file details and also contributing.md file
- use your creativity to make REAME.md beautiful and easily understandable

**Comment by codeboyfriend** [comment]
Can I work on this?

**Comment by RakeshSangem** [comment]
> Can I work on this?

Sure, Assigned✅

**Comment by asdsyd** [comment]
Can I work on this ?

**Comment by asdsyd** [comment]
@RakeshSangem . This is done . Take a look

**Comment by asdsyd** [comment]
@RakeshSangem ??

**Comment by asdsyd** [comment]
@RakeshSangem I have made a PR. Please look into it.

**Comment by RakeshSangem** [comment]
I have decided to go with the current README.md file. Thanks for contribution and time.
