### ISSUE TITLE
 [FEATURE] Add skills section

### ISSUE THREAD

**Issue by coder-chahal** [RakeshSangem/portfolio#17]
### Add a skill section in portfolio**

something like this

![issue](https://user-images.githubusercontent.com/110322061/194852518-b7416ba4-3660-4b15-9d2f-30ad69fe8ee6.png)

**Comment by coder-chahal** [comment]
hey @RakeshSangem, i want to work on in it..
please assign this issue to me:(

**Comment by RakeshSangem** [comment]
Hey @coder-chahal, Thanks for raising an issue. Could you tell more how you will implement so that I'll get better idea.

**Comment by coder-chahal** [comment]
i implement something.

![iss](https://user-images.githubusercontent.com/110322061/194862731-84b7ac01-4271-4e79-9657-faeb6334ad74.png)

**Comment by coder-chahal** [comment]
how is it ? can i commit changes

**Comment by RakeshSangem** [comment]
> ![issue](https://user-images.githubusercontent.com/110322061/194852518-b7416ba4-3660-4b15-9d2f-30ad69fe8ee6.png)

Could you do this? I'm not going to use the percentage thing. Also, I prefer not to use anyone else.

**Comment by coder-chahal** [comment]
Sir can you please tell which skills i add?

**Comment by RakeshSangem** [comment]
> Sir can you please tell which skills i add?

Could you check the GitHub profile? There all the tech stack is listed. Let me know if you need any further help:)
