### ISSUE TITLE
[FEATURE] Add Contact Me Page

### ISSUE THREAD

**Issue by zelfroster** [RakeshSangem/portfolio#19]
### Is your feature request related to a problem? Please describe.**
Currently the portfolio doesn't have a Contact page which is necessary.
### Describe the solution you'd like**
I will create a **Contact Me** page for it

**Comment by RakeshSangem** [comment]
Thanks for raising an issue. I assisted this ticket to you⚡

**Comment by NizarAhamed97** [comment]
I would like to work on the issue,Is it still open?

**Comment by zelfroster** [comment]
I have almost finished working on it 😅

**Comment by RakeshSangem** [comment]
@NizarAhamed97 you can check others or you can create a new issue.

**Comment by RakeshSangem** [comment]
> I have almost finished working on it 😅

Looking forward to see it:)
