### ISSUE TITLE
[FEATURE] Improve Nav bar

### ISSUE THREAD

**Issue by Chaitanya1603** [RakeshSangem/portfolio#22]
### Is your feature request related to a problem? Please describe.**

Nav bar is not looking attractive

### Describe the solution you'd like**
Add Underline on hover in nav bar

**Comment by Chaitanya1603** [comment]
@RakeshSangem  assign this issue to me and add Hacktoberfest label

**Comment by Yashpsct010** [comment]
Assign me this issue

**Comment by RakeshSangem** [comment]
Hello, @Yashpsct010! What changes do you wish to make? Could you please provide more information?

**Comment by prashant-jadu** [comment]
can you please assign this issue to me and add Hacktoberfest label for this?

**Comment by RakeshSangem** [comment]
I have decided to keep it simple, so for that reason closing this issue.
