### ISSUE TITLE
Improve footer bar

### ISSUE THREAD

**Issue by asdsyd** [RakeshSangem/portfolio#27]
Footer bar could be improved
**Screenshots**
![Screenshot 2022-10-12 at 10 09 52 PM](https://user-images.githubusercontent.com/77977076/195400247-2f6dfd7b-7a86-4a82-9dee-2e2b8eeb3d63.png)

**Comment by asdsyd** [comment]
I would like to work on this issue. Please add hacktoberfest label

**Comment by RakeshSangem** [comment]
Hallo @asdsyd Could you elaborate on how you intend to enhance the footer?

**Comment by therealashugarg** [comment]
can i work on this task ?

**Comment by RakeshSangem** [comment]
I appreciate the question, and I believe @asdsyd is working on it. We'll see what he says once we wait. We'll assign this to you if we don't hear back. You are welcome to browse the site and you can raise an issue.

**Comment by RakeshSangem** [comment]
Hey @asdsyd  Nice, You can go with first inspiration.

**Comment by asdsyd** [comment]
@RakeshSangem you mean 'made with love' one ?

**Comment by RakeshSangem** [comment]
> @RakeshSangem you mean 'made with love' one ?

Yes, but we don't need that `opportunities` thing and the social icons should be aligned in center.

**Comment by asdsyd** [comment]
Hey @RakeshSangem . It's done , take a look at PR. Thanks.
