### ISSUE TITLE
[BUG] Flex box issue

### ISSUE THREAD

**Issue by asdsyd** [RakeshSangem/portfolio#28]
**Describe the bug**
The input fields aren't aligned into the div
**To Reproduce**
Make your browser use half of your screen(split screen)
**Expected behavior**
Input fields to coincide the box.
**Screenshots**
![Screenshot 2022-10-12 at 10 12 12 PM](https://user-images.githubusercontent.com/77977076/195400772-7eeaee57-b3f6-4be7-9a50-e6f37a4f06be.png)

**Additional context**
None

**Comment by RakeshSangem** [comment]
Hey @zelfroster Could you look into the issue.

**Comment by zelfroster** [comment]
Yes, I can fix it. I will work on it now, assign it to me.
