### ISSUE TITLE
adding hovering state to all the skills .

### ISSUE THREAD

**Issue by Bharath292003** [RakeshSangem/portfolio#29]

**Comment by Bharath292003** [comment]
add*

**Comment by RakeshSangem** [comment]
Could elaborate more to give me a better understanding of the adjustments you'd want to see.

**Comment by RakeshSangem** [comment]
> > Could elaborate more to give me a better understanding of the adjustments you'd want to see.
> 
> u have added ur skills (html,css,javascript etc).so i meant adding hovering color to those icons(html,css,javascript,figma etc.)

Assigned✅

**Comment by Yashpsct010** [comment]
Please assign me

**Comment by RakeshSangem** [comment]
Issue resolved.(#39 )
