### ISSUE TITLE
[FEATURE] Owl Carousel for Projects section

### ISSUE THREAD

**Issue by MaruthiKo** [RakeshSangem/portfolio#35]
### Is your feature request related to a problem? Please describe.**
Instead of stacking the projects adding an automatic owl carousel would like great in my opinion
### Describe the solution you'd like**
Converting the stack of projects section into an owl carousel

**Comment by RakeshSangem** [comment]
Hey @MaruthiKo, Could you give me some reference screenshots that would be great!

**Comment by MaruthiKo** [comment]
![maxresdefault](https://user-images.githubusercontent.com/63769209/195732004-34b933f7-43ff-4d6e-b813-cacb86765a05.jpg)
It would look something like this and we can make it automatic

**Comment by RakeshSangem** [comment]
Looks good:)

**Comment by RakeshSangem** [comment]
Assigned ✅

**Comment by MaruthiKo** [comment]
Alright working on it

**Comment by MaruthiKo** [comment]
Hey @RakeshSangem, I have already made the necessary changes and added a PR, please have a look at it and let me know about any changes
