### ISSUE TITLE
[FEATURE] Implement @media queries so the website is responsive

### ISSUE THREAD

**Issue by abitsalihu** [RakeshSangem/portfolio#4]
**Is your feature request related to a problem? Please describe.**

I noticed that the website has problems when scaled down, especially the nav.

**Describe the solution you'd like**

I would like to contribute by adding media queries and making the website responsive through all the platforms!

Below is a video of the website responsiveness at the moment:

https://user-images.githubusercontent.com/94648837/192095749-60984125-1163-42f8-9ccf-d17c27210287.mov

**Comment by RakeshSangem** [comment]
Yeah, I have started yesterday only. 

Thanks for raising an issue. I am gonna assign this ticket to you.

**Comment by abitsalihu** [comment]
@RakeshSangem Alright I'll try and implement it now. :)
