### ISSUE TITLE
changing favicon color.

### ISSUE THREAD

**Issue by Bharath292003** [RakeshSangem/portfolio#43]
changing favicon color from R(black) to R(white or ur preffered color).
favicon is not properly visible as  it is completely black in color.

**Comment by RakeshSangem** [comment]
Hey @Bharath292003, you still wanna work on it?

**Comment by RakeshSangem** [comment]
> > Hey @Bharath292003, you still wanna work on it?
> 
> yeah sure rakesh,may ik your preffered color for favicon?shall i stick with white itself?

It should work with dark and light mode if it's possible.
