### ISSUE TITLE
[FEATURE] create footer at the end of website.

### ISSUE THREAD

**Issue by RakeshSangem** [RakeshSangem/portfolio#6]
### Is your feature request related to a problem? Please describe.**
Currently, website doesn't have any footer so it will look good if we add footer.

**Comment by NisooJadhav** [comment]
Hi, there!
Can I work on it?
You can have a look at my portfolio [nisootech.vercel.app](https://nisootech.vercel.app)

**Comment by RakeshSangem** [comment]
> Hi, there!
> Can I work on it?
> You can have a look at my portfolio [nisootech.vercel.app](https://nisootech.vercel.app)

Awesome, go ahead. Keep it clean and simple:)

**Comment by NisooJadhav** [comment]
> > Hi, there!
> > Can I work on it?
> > You can have a look at my portfolio [nisootech.vercel.app](https://nisootech.vercel.app)
> 
> Awesome, go ahead. Keep it clean and simple:)

sure

**Comment by NisooJadhav** [comment]
Made a footer that looks like this:
### **PC:**
![footer_1](https://user-images.githubusercontent.com/68807845/192290412-44b4681f-7e04-493f-8d59-c8c8a316112f.png)

### **Mobile:**
![footer_2](https://user-images.githubusercontent.com/68807845/192290446-522dea0b-6954-46e2-b397-5c5651f59633.png)

Is this what you were looking for? any improvements? or I send the PR.

**Comment by RakeshSangem** [comment]
Hey @NisooJadhav , Could you make it like as shown in below picture?

![sample footer](https://user-images.githubusercontent.com/107752425/192296417-0f77587e-6908-4c37-95df-3e7b4def7e82.png)

**Comment by NisooJadhav** [comment]
@RakeshSangem sure, you want it centered? will do it

**Comment by RakeshSangem** [comment]
> @RakeshSangem sure, you want it centered? will do it

Centered looks good in my opinion:)

**Comment by NisooJadhav** [comment]
Centered Footer.
### **PC:**
![pc](https://user-images.githubusercontent.com/68807845/192413026-710182f2-9570-40fc-a1c4-c37117e38949.png)

### **Mobile:**
![mobile](https://user-images.githubusercontent.com/68807845/192413069-365be602-5d1e-4e68-b2c9-285b3877b90e.png)

Shall I open a PR now, any changes?

**Comment by RakeshSangem** [comment]
hey @NisooJadhav , Looks good to me, you can create PR for this.
