### ISSUE TITLE
[FEATURE] add hover effects to navigation links

### ISSUE THREAD

**Issue by RakeshSangem** [RakeshSangem/portfolio#7]
### Is your feature request related to a problem? Please describe.**
currently, we don't have any hover state for navigation links. It looks good when we have hover state in Desktop.

**Comment by dhruvdabhi101** [comment]
I would like to work on this issue.

**Comment by RakeshSangem** [comment]
> I would like to work on this issue.

Awesome, Go ahead. I would suggest you to use blue color:)

**Comment by dhruvdabhi101** [comment]
Do I have to do anything for Icons.. Like Github and Twitter ?

**Comment by RakeshSangem** [comment]
You can:) same blue color
